 Database xtimeml-references  running on 127.0.0.1

# phpMyAdmin SQL Dump
# version 2.5.3-rc1
# http://www.phpmyadmin.net
#
# Host: 127.0.0.1
# Generation Time: Jan 10, 2008 at 08:25 AM
# Server version: 4.0.14
# PHP Version: 4.4.7
# 
# Database : `xtimeml-references`
# 

# --------------------------------------------------------

#
# Table structure for table `refs-history`
#

DROP TABLE IF EXISTS `refs-history`;
CREATE TABLE `refs-history` (
  `id` int(11) NOT NULL auto_increment,
  `refid` int(11) NOT NULL default '0',
  `timestamp` timestamp(14) NOT NULL,
  `year` smallint(6) NOT NULL default '0',
  `author` varchar(255) NOT NULL default '',
  `title` varchar(255) NOT NULL default '',
  `keywords` varchar(255) NOT NULL default '',
  `html` text NOT NULL,
  `bibtex` text NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `refid` (`refid`)
) TYPE=MyISAM AUTO_INCREMENT=66 ;

#
# Dumping data for table `refs-history`
#

INSERT INTO `refs-history` VALUES (19, 6, 20080108193411, 1997, 'David Day and John Aberdeen and Lynette Hirschman and Robyn Kozierok and Patricia Robinson and Marc Vilain', 'Mixed-Initiative Development of Language Processing Systems', 'annotation ; tools', '', '@inproceedings{Alembic,\r\n  author	= "David Day and John Aberdeen and Lynette Hirschman and Robyn Kozierok and Patricia Robinson and Marc Vilain",\r\n  title		= "{Mixed-Initiative Development of Language Processing Systems}",\r\n  booktitle	= "Fifth Conference on Applied Natural Language Processing Systems",\r\n  year		= "1997",\r\n  pages		= "88--95",\r\n  address	= "Washington D.C., U.S.A."\r\n}');
INSERT INTO `refs-history` VALUES (20, 6, 20080108194045, 1997, 'David Day and John Aberdeen and Lynette Hirschman and Robyn Kozierok and Patricia Robinson and Marc Vilain', 'Mixed-Initiative Development of Language Processing Systems', 'annotation ; tools', '', '@inproceedings{Alembic,\r\n  author	= "David Day and John Aberdeen and Lynette Hirschman and Robyn Kozierok\r\n                   and Patricia Robinson and Marc Vilain",\r\n  title		= "{Mixed-Initiative Development of Language Processing Systems}",\r\n  booktitle	= "Fifth Conference on Applied Natural Language Processing Systems",\r\n  year		= "1997",\r\n  pages		= "88--95",\r\n  address	= "Washington D.C., U.S.A."\r\n}');
INSERT INTO `refs-history` VALUES (21, 7, 20080108212615, 2005, 'Marc Verhagen', 'Drawing TimeML Relations with T-BOX', 'temporal reasoning ; timeml ; tools ; visualization', '', '@InProceedings{verhagen:2005b,\r\n  author =      {Marc Verhagen},\r\n  title =       {Drawing {T}ime{ML} Relations with {T-BOX}},\r\n  booktitle =   {Annotating, Extracting and Reasoning about Time and Events},\r\n  year =        {2005},\r\n  editor =      {Graham Katz and James Pustejovsky and Frank Schilder},\r\n  number =      {05151},\r\n  series =      {Dagstuhl Seminar Proceedings},\r\n  ISSN =        {1862-4405},\r\n  publisher =   {Internationales Begegnungs- und Forschungszentrum fuer Informatik (IBFI), \r\n                 Schloss Dagstuhl, Germany},\r\n  OPTaddress =  {Dagstuhl, Germany},\r\n  OPTURL =      {http://drops.dagstuhl.de/opus/volltexte/2005/318\r\n                 [date of citation: 2005-01-01]},\r\n  note =        {$<$http://drops.dagstuhl.de/opus/volltexte/2005/318$>$\r\n                 [date of citation: 2005-01-01]},\r\n  OPTannote =   {Keywords: Annotation, visualization, temporal annotation},\r\n}');
INSERT INTO `refs-history` VALUES (22, 8, 20080108212846, 2005, 'Marc Verhagen and Inderjeet Mani and Roser Sauri and Jessica Littman', 'Automating Temporal Annotation with TARSQI', 'annotation ; tarsqi ; temporal links ; timeml', '', '@inproceedings{tarsqi:2005,\r\n  author    = {Marc Verhagen and Inderjeet Mani and Roser Sauri and Jessica Littman \r\n               and Robert Knippen and Seok Bae Jang and Anna Rumshisky and John Phillips \r\n               and James Pustejovsky},\r\n  title     = {Automating Temporal Annotation with {TARSQI}},\r\n  booktitle = "Proceedings of the 43th Annual Meeting of the Association for \r\n               Computational Linguistics",\r\n  year      = 2005,\r\n  note      = "Demo session",\r\n  address   = "Ann Arbor, USA"\r\n}');
INSERT INTO `refs-history` VALUES (23, 9, 20080108213048, 202, 'James Pustejovsky and Luc Belanger and Jose Casta{\\~n}o and Robert Gaizauskas and Patrick Hanks and Bob Ingria and Graham Katz and Dragomir Radev and Anna Rumshishky and Antonio Sanfilippo and Roser Saur{\\\'i} and Andrea Setzer and Beth Sundheim and Marc V', 'TERQAS Final Report', 'annotation ; events ; temporal links ; time expressions ; tools', '', '@techreport{Terqas:2002,\r\n  author      	= "James Pustejovsky and Luc Belanger and Jose Casta{\\~n}o \r\n                   and Robert Gaizauskas and Patrick Hanks and Bob Ingria \r\n                   and Graham Katz and Dragomir Radev and Anna Rumshishky \r\n                   and Antonio Sanfilippo and Roser Saur{\\\'i} and Andrea Setzer \r\n                   and Beth Sundheim and Marc Verhagen",\r\n  title       	= "{TERQAS Final Report}",\r\n  year        	= 2002,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-history` VALUES (24, 9, 20080108213201, 202, 'James Pustejovsky, Luc Belanger, Jose Casta{\\~n}o, Robert Gaizauskas, Patrick Hanks, Bob Ingria, Graham Katz, Dragomir Radev, Anna Rumshishky, Antonio Sanfilippo, Roser Saur{\\\'i}, Andrea Setzer, Beth Sundheim, Marc Verhagen', 'TERQAS Final Report', 'annotation ; events ; temporal links ; time expressions ; tools', '', '@techreport{Terqas:2002,\r\n  author      	= "James Pustejovsky and Luc Belanger and Jose Casta{\\~n}o \r\n                   and Robert Gaizauskas and Patrick Hanks and Bob Ingria \r\n                   and Graham Katz and Dragomir Radev and Anna Rumshishky \r\n                   and Antonio Sanfilippo and Roser Saur{\\\'i} and Andrea Setzer \r\n                   and Beth Sundheim and Marc Verhagen",\r\n  title       	= "{TERQAS Final Report}",\r\n  year        	= 2002,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-history` VALUES (25, 9, 20080108213217, 2002, 'James Pustejovsky, Luc Belanger, Jose Casta{\\~n}o, Robert Gaizauskas, Patrick Hanks, Bob Ingria, Graham Katz, Dragomir Radev, Anna Rumshishky, Antonio Sanfilippo, Roser Saur{\\\'i}, Andrea Setzer, Beth Sundheim, Marc Verhagen', 'TERQAS Final Report', 'annotation ; events ; temporal links ; time expressions ; tools', '', '@techreport{Terqas:2002,\r\n  author      	= "James Pustejovsky and Luc Belanger and Jose Casta{\\~n}o \r\n                   and Robert Gaizauskas and Patrick Hanks and Bob Ingria \r\n                   and Graham Katz and Dragomir Radev and Anna Rumshishky \r\n                   and Antonio Sanfilippo and Roser Saur{\\\'i} and Andrea Setzer \r\n                   and Beth Sundheim and Marc Verhagen",\r\n  title       	= "{TERQAS Final Report}",\r\n  year        	= 2002,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-history` VALUES (26, 10, 20080108213330, 2003, 'James Pustejovsky and Inderjeet Mani and Luc Belanger and Linda van Guilder and Robert Knippen and Andrew See and Jon Schwarz and Marc Verhagen', 'TANGO Final Report', 'annotation ; tools', '', '@techreport{Tango:2003,\r\n  author      	= "James Pustejovsky and Inderjeet Mani and Luc Belanger \r\n                   and Linda van Guilder and Robert Knippen and Andrew See \r\n                   and Jon Schwarz and Marc Verhagen",\r\n  title       	= "{TANGO Final Report}",\r\n  year        	= 2003,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-history` VALUES (27, 11, 20080108213442, 2003, 'David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} and Andrew See and Andrea Setzer and Beth Sundheim', 'The TimeBank Corpus', 'annotation ; timeml', '', '@article{TimeBank,\r\n  author		= "David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} and Andrew See and Andrea Setzer and Beth Sundheim",\r\n  title		= "{The TimeBank Corpus}",\r\n  journal	= "Corpus Linguistics",\r\n  year		= 2003,\r\n  month		= "March",\r\n  address	= "Lancaster, UK"\r\n}');
INSERT INTO `refs-history` VALUES (28, 11, 20080108213502, 2003, 'David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} and Andrew See and Andrea Setzer and Beth Sundheim', 'The TimeBank Corpus', 'annotation ; timeml', '', '@article{TimeBank,\r\n  author	= "David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks \r\n                   and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} \r\n                   and Andrew See and Andrea Setzer and Beth Sundheim",\r\n  title		= "{The TimeBank Corpus}",\r\n  journal	= "Corpus Linguistics",\r\n  year		= 2003,\r\n  month		= "March",\r\n  address	= "Lancaster, UK"\r\n}');
INSERT INTO `refs-history` VALUES (29, 12, 20080108214846, 2003, 'James Pustejovsky and José Castaño and Robert Ingria and Roser Saurí and Robert Gaizauskas and Andrea Setzer and Graham Katz', 'TimeML: Robust Specification of Event and Temporal Expressions in Text', 'timeml', '', '\r\n@inproceedings{TimeML,\r\n  author	= "James Pustejovsky and Jos{\\\'e} Casta{\\~n}o and Robert Ingria \r\n                   and Roser Saur{\\\'i} and Robert Gaizauskas and Andrea Setzer \r\n                   and Graham Katz",\r\n  title		= "{TimeML: Robust Specification of Event and Temporal Expressions in Text}",\r\n  booktitle	= "IWCS-5 Fifth International Workshop on Computational Semantics",\r\n  year		= 2003\r\n}');
INSERT INTO `refs-history` VALUES (44, 11, 20080109002912, 2003, 'David Day, Lisa Ferro, Robert Gaizauskas, Patrick Hanks, Marcia Lazo, James Pustejovsky, Roser Saurí, Andrew See, Andrea Setzer, and Beth Sundheim', 'The TimeBank Corpus', 'annotation ; timeml', '', '@article{TimeBank,\r\n  author	= "David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks \r\n                   and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} \r\n                   and Andrew See and Andrea Setzer and Beth Sundheim",\r\n  title		= "{The TimeBank Corpus}",\r\n  journal	= "Corpus Linguistics",\r\n  year		= 2003,\r\n  month		= "March",\r\n  address	= "Lancaster, UK"\r\n}');
INSERT INTO `refs-history` VALUES (31, 14, 20080108215923, 2005, 'Marc Verhagen', 'Temporal Closure in an Annotation Environment', 'annotation ; temporal links ; temporal reasoning ; tools', 'Marc Verhagen. 2005. Temporal Closure in an Annotation Environment. <i>Language Resources and Evaluation</i>, Volume 39, May 2005, pp 211-241, Springer.', '@article{closure:2005,\r\n  author    = "Marc Verhagen",\r\n  title     = "Temporal Closure in an Annotation Environment",\r\n  journal   = "Language Resources and Evaluation",\r\n  year      = 2005,\r\n  month     = May,\r\n  volume    = 39,\r\n  pages     = "211-241",\r\n  publisher = "Springer"\r\n}');
INSERT INTO `refs-history` VALUES (32, 15, 20080108220516, 2005, 'James Pustejovsky, Robert Knippen, Jessica Littman, and Roser Saurí', 'Temporal and Event Information in Natural Language Text', 'annotation ; events ; time expressions ; timeml', '', '@article{timeml:2005,\r\n  author = "James Pustejovsky and Robert Knippen and Jessica Littman and Roser Saur\\\'i",\r\n  title = "Temporal and Event Information in Natural Language Text",\r\n  journal = "Language Resources and Evaluation",\r\n  year = 2005,\r\n  month = May,\r\n  volume = 39,\r\n  pages = "123-164",\r\n  publisher = "Springer"\r\n}');
INSERT INTO `refs-history` VALUES (33, 16, 20080108220711, 2005, 'Dick Crouch and Roser Saurí and Abraham Fowler', 'AQUAINT Pilot Knowledge-Based Evaluation: Annotation Guidelines', 'annotation', '', '@techreport{kb-eval,\r\n  author = "Dick Crouch and Roser Saur\\\'{\\i} and Abraham Fowler",\r\n  title = "AQUAINT Pilot Knowledge-Based Evaluation: Annotation Guidelines",\r\n  year = 2005,\r\n  month = May,\r\n  institution = "Palo Alto Research Center"\r\n}');
INSERT INTO `refs-history` VALUES (34, 17, 20080108221042, 2005, 'Roser Saurí and Marc Verhagen', 'Temporal Information in Intensional Contexts', 'temporal links ; timeml', '', '@inproceedings{slinket-iwcs05,\r\n  author    = "Roser Saur{\\\'i} and Marc Verhagen",\r\n  title     = "Temporal Information in Intensional Contexts",\r\n  booktitle = "Proceedings of the Sixth International Workshop on Computation Semantics (IWCS-6)",\r\n  year      = 2005,\r\n  address   = "Tilburg, Netherlands"\r\n}');
INSERT INTO `refs-history` VALUES (35, 18, 20080108221226, 2005, 'Roser Saurí, Robert Knippen, Marc Verhagen, and James Pustejovsky', 'Evita: A Robust Event Recognizer For QA Systems', 'events ; tarsqi ; timeml', '', '@inproceedings{evita-htl05,\r\n  author = "Roser Saur{\\\'i} and Robert Knippen and Marc Verhagen and James Pustejovsky",\r\n  title = "{Evita}: A Robust Event Recognizer For QA Systems",\r\n  booktitle = "Proceedings of the HLT/EMNLP 2005",\r\n  pages = "700-707",\r\n  year = 2005\r\n}');
INSERT INTO `refs-history` VALUES (36, 19, 20080108221627, 2006, 'Roser Saurí, Marc Verhagen, and James Pustejovsky', 'Annotating and Recognizing Event Modality in Text', 'events ; tarsqi', '', '@inproceedings{evita-aaai06,\r\n  author    = "Roser Saur{\\\'i} and Marc Verhagen and James Pustejovsky",\r\n  title     = "Annotating and Recognizing Event Modality in Text",\r\n  booktitle = "(AAAI 2006)",\r\n  year      = 2006\r\n}');
INSERT INTO `refs-history` VALUES (37, 20, 20080108221739, 2006, 'Roser Saurí, Marc Verhagen, and James Pustejovsky', 'SlinkET}: A Partial Modal Parser for Events', 'events ; tarsqi ; temporal links ; tools', '', '@inproceedings{slinket-lrec,\r\nauthor = "Roser Saur{\\\'i} and Marc Verhagen and James Pustejovsky",\r\ntitle = "{SlinkET}: A Partial Modal Parser for Events",\r\nbooktitle = "Language Resources and Evaluation Conference, {LREC 2006}",\r\nyear = "2006",\r\naddress = "Genoa, Italy" \r\n}');
INSERT INTO `refs-history` VALUES (38, 21, 20080108221841, 2006, 'Marc Verhagen and Robert Knippen and Inderjeet Mani and James Pustejovsky', 'Annotation of Temporal Relations with Tango', 'annotation ; temporal links ; tools', '', '@inproceedings{tango-lrec,\r\n  author = "Marc Verhagen and Robert Knippen and Inderjeet Mani and James Pustejovsky",\r\n  title = "Annotation of Temporal Relations with {Tango}",\r\n  booktitle = "Language Resources and Evaluation Conference, {LREC 2006}",\r\n  year = "2006",\r\n  address = "Genoa, Italy" \r\n}');
INSERT INTO `refs-history` VALUES (39, 20, 20080108230400, 2006, 'Roser Saurí, Marc Verhagen, and James Pustejovsky', 'SlinkET: A Partial Modal Parser for Events', 'events ; tarsqi ; temporal links ; tools', '', '@inproceedings{slinket-lrec,\r\n  author    = "Roser Saur{\\\'i} and Marc Verhagen and James Pustejovsky",\r\n  title     = "{SlinkET}: A Partial Modal Parser for Events",\r\n  booktitle = "Language Resources and Evaluation Conference, {LREC 2006}",\r\n  year      = "2006",\r\n  address   = "Genoa, Italy" \r\n}');
INSERT INTO `refs-history` VALUES (40, 21, 20080109000054, 2006, 'Marc Verhagen and Robert Knippen and Inderjeet Mani and James Pustejovsky', 'Annotation of Temporal Relations with Tango', 'annotation ; tarsqi ; temporal links ; tools', '', '@inproceedings{tango-lrec,\r\n  author = "Marc Verhagen and Robert Knippen and Inderjeet Mani and James Pustejovsky",\r\n  title = "Annotation of Temporal Relations with {Tango}",\r\n  booktitle = "Language Resources and Evaluation Conference, {LREC 2006}",\r\n  year = "2006",\r\n  address = "Genoa, Italy" \r\n}');
INSERT INTO `refs-history` VALUES (41, 11, 20080109000341, 2003, 'David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks and Marcia Lazo and James Pustejovsky and Roser Saurí and Andrew See and Andrea Setzer and Beth Sundheim', 'The TimeBank Corpus', 'annotation ; timeml', '', '@article{TimeBank,\r\n  author	= "David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks \r\n                   and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} \r\n                   and Andrew See and Andrea Setzer and Beth Sundheim",\r\n  title		= "{The TimeBank Corpus}",\r\n  journal	= "Corpus Linguistics",\r\n  year		= 2003,\r\n  month		= "March",\r\n  address	= "Lancaster, UK"\r\n}');
INSERT INTO `refs-history` VALUES (42, 21, 20080109001701, 2006, 'Marc Verhagen, Robert Knippen, Inderjeet Mani, and James Pustejovsky', 'Annotation of Temporal Relations with Tango', 'annotation ; tarsqi ; temporal links ; tools', '', '@inproceedings{tango-lrec,\r\n  author = "Marc Verhagen and Robert Knippen and Inderjeet Mani and James Pustejovsky",\r\n  title = "Annotation of Temporal Relations with {Tango}",\r\n  booktitle = "Language Resources and Evaluation Conference, {LREC 2006}",\r\n  year = "2006",\r\n  address = "Genoa, Italy" \r\n}');
INSERT INTO `refs-history` VALUES (43, 8, 20080109001854, 2005, 'Marc Verhagen, Inderjeet Mani, Roser Sauri, Jessica Littman, Robert Knippen, Seok Bae Jang, Anna Rumshisky, John Phillips, and James Pustejovsky', 'Automating Temporal Annotation with TARSQI', 'annotation ; tarsqi ; temporal links ; timeml', '', '@inproceedings{tarsqi:2005,\r\n  author    = {Marc Verhagen and Inderjeet Mani and Roser Sauri and Jessica Littman \r\n               and Robert Knippen and Seok Bae Jang and Anna Rumshisky and John Phillips \r\n               and James Pustejovsky},\r\n  title     = {Automating Temporal Annotation with {TARSQI}},\r\n  booktitle = "Proceedings of the 43th Annual Meeting of the Association for \r\n               Computational Linguistics",\r\n  year      = 2005,\r\n  note      = "Demo session",\r\n  address   = "Ann Arbor, USA"\r\n}');
INSERT INTO `refs-history` VALUES (45, 16, 20080109003243, 2005, 'Dick Crouch, Roser Saurí, and Abraham Fowler', 'AQUAINT Pilot Knowledge-Based Evaluation: Annotation Guidelines', 'annotation ; llc ; tarsqi', '', '@techreport{kb-eval,\r\n  author = "Dick Crouch and Roser Saur\\\'{\\i} and Abraham Fowler",\r\n  title = "AQUAINT Pilot Knowledge-Based Evaluation: Annotation Guidelines",\r\n  year = 2005,\r\n  month = May,\r\n  institution = "Palo Alto Research Center"\r\n}');
INSERT INTO `refs-history` VALUES (46, 10, 20080109003410, 2003, 'James Pustejovsky, Inderjeet Mani, Luc Belanger, Linda van Guilder, Robert Knippen, Andrew See, Jon Schwarz, and Marc Verhagen', 'TANGO Final Report', 'annotation ; llc ; tarsqi ; tools ; visualization', '', '@techreport{Tango:2003,\r\n  author      	= "James Pustejovsky and Inderjeet Mani and Luc Belanger \r\n                   and Linda van Guilder and Robert Knippen and Andrew See \r\n                   and Jon Schwarz and Marc Verhagen",\r\n  title       	= "{TANGO Final Report}",\r\n  year        	= 2003,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-history` VALUES (47, 12, 20080109003710, 2003, 'James Pustejovsky, José Castaño, Robert Ingria, Roser Saurí, Robert Gaizauskas, Andrea Setzer, and Graham Katz', 'TimeML: Robust Specification of Event and Temporal Expressions in Text', 'llc ; tarsqi ; timeml', '', '@inproceedings{TimeML,\r\n  author	= "James Pustejovsky and Jos{\\\'e} Casta{\\~n}o and Robert Ingria \r\n                   and Roser Saur{\\\'i} and Robert Gaizauskas and Andrea Setzer \r\n                   and Graham Katz",\r\n  title		= "{TimeML: Robust Specification of Event and Temporal Expressions in Text}",\r\n  booktitle	= "IWCS-5 Fifth International Workshop on Computational Semantics",\r\n  year		= 2003\r\n}');
INSERT INTO `refs-history` VALUES (48, 6, 20080109003739, 1997, 'David Day, John Aberdeen, Lynette Hirschman, Robyn Kozierok, Patricia Robinson, and Marc Vilain', 'Mixed-Initiative Development of Language Processing Systems', 'annotation ; tools', '', '@inproceedings{Alembic,\r\n  author	= "David Day and John Aberdeen and Lynette Hirschman and Robyn Kozierok\r\n                   and Patricia Robinson and Marc Vilain",\r\n  title		= "{Mixed-Initiative Development of Language Processing Systems}",\r\n  booktitle	= "Fifth Conference on Applied Natural Language Processing Systems",\r\n  year		= "1997",\r\n  pages		= "88--95",\r\n  address	= "Washington D.C., U.S.A."\r\n}');
INSERT INTO `refs-history` VALUES (49, 9, 20080109003839, 2002, 'James Pustejovsky, Luc Belanger, José Castaño, Robert Gaizauskas, Patrick Hanks, Bob Ingria, Graham Katz, Dragomir Radev, Anna Rumshishky, Antonio Sanfilippo, Roser Saurí, Andrea Setzer, Beth Sundheim, Marc Verhagen', 'TERQAS Final Report', 'annotation ; events ; llc ; tarsqi ; temporal links ; time expressions ; tools', '', '@techreport{Terqas:2002,\r\n  author      	= "James Pustejovsky and Luc Belanger and Jose Casta{\\~n}o \r\n                   and Robert Gaizauskas and Patrick Hanks and Bob Ingria \r\n                   and Graham Katz and Dragomir Radev and Anna Rumshishky \r\n                   and Antonio Sanfilippo and Roser Saur{\\\'i} and Andrea Setzer \r\n                   and Beth Sundheim and Marc Verhagen",\r\n  title       	= "{TERQAS Final Report}",\r\n  year        	= 2002,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-history` VALUES (50, 11, 20080109003924, 2003, 'David Day, Lisa Ferro, Robert Gaizauskas, Patrick Hanks, Marcia Lazo, James Pustejovsky, Roser Saurí, Andrew See, Andrea Setzer, and Beth Sundheim', 'The TimeBank Corpus', 'annotation ; llc ; tarsqi ; timeml', '', '@article{TimeBank,\r\n  author	= "David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks \r\n                   and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} \r\n                   and Andrew See and Andrea Setzer and Beth Sundheim",\r\n  title		= "{The TimeBank Corpus}",\r\n  journal	= "Corpus Linguistics",\r\n  year		= 2003,\r\n  month		= "March",\r\n  address	= "Lancaster, UK"\r\n}');
INSERT INTO `refs-history` VALUES (51, 22, 20080109010233, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'Learning Event Durations from Event Descriptions', 'annotation ; events ; tarsqi', '', '@InProceedings{ pan2006a,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {Learning Event Durations from Event Descriptions},\r\n  booktitle = {Proceedings of the 44th Annual Meeting of the Association for Computational Linguistics (COLING-ACL)},\r\n  pages     = {393-400},\r\n  year      = {2006},\r\n  address   = {Sydney, Australia}\r\n}');
INSERT INTO `refs-history` VALUES (52, 22, 20080109010257, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'Learning Event Durations from Event Descriptions', 'annotation ; events ; machine learning ; tarsqi', '', '@InProceedings{ pan2006a,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {Learning Event Durations from Event Descriptions},\r\n  booktitle = {Proceedings of the 44th Annual Meeting of the Association for Computational Linguistics (COLING-ACL)},\r\n  pages     = {393-400},\r\n  year      = {2006},\r\n  address   = {Sydney, Australia}\r\n}');
INSERT INTO `refs-history` VALUES (53, 23, 20080109010421, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'An Annotated Corpus of Typical Durations of Events', 'annotation ; events', '', '@InProceedings{ pan2006b,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {An Annotated Corpus of Typical Durations of Events},\r\n  booktitle = {Proceedings of the Fifth International Conference on Language Resources and Evaluation (LREC)},\r\n  pages     = {77-83},\r\n  year      = {2006},\r\n  address   = {Genoa, Italy}\r\n}');
INSERT INTO `refs-history` VALUES (54, 24, 20080109010554, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'Extending TimeML with Typical Durations of Events', 'events ; tarsqi ; timeml', '', '@InProceedings{ pan2006c,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {Extending TimeML with Typical Durations of Events},\r\n  booktitle = {Proceedings of Annotating and Reasoning about Time and Events workshop at the 44th Annual Meeting of the Association for Computational Linguistics (COLING-ACL)},\r\n  pages     = {38-45},\r\n  year      = {2006},\r\n  address   = {Sydney, Australia}\r\n}');
INSERT INTO `refs-history` VALUES (55, 23, 20080109010613, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'An Annotated Corpus of Typical Durations of Events', 'annotation ; events ; tarsqi', '', '@InProceedings{ pan2006b,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {An Annotated Corpus of Typical Durations of Events},\r\n  booktitle = {Proceedings of the Fifth International Conference on Language Resources and Evaluation (LREC)},\r\n  pages     = {77-83},\r\n  year      = {2006},\r\n  address   = {Genoa, Italy}\r\n}');
INSERT INTO `refs-history` VALUES (56, 7, 20080109010626, 2005, 'Marc Verhagen', 'Drawing TimeML Relations with T-BOX', 'tarsqi ; temporal reasoning ; timeml ; tools ; visualization', '', '@InProceedings{verhagen:2005b,\r\n  author =      {Marc Verhagen},\r\n  title =       {Drawing {T}ime{ML} Relations with {T-BOX}},\r\n  booktitle =   {Annotating, Extracting and Reasoning about Time and Events},\r\n  year =        {2005},\r\n  editor =      {Graham Katz and James Pustejovsky and Frank Schilder},\r\n  number =      {05151},\r\n  series =      {Dagstuhl Seminar Proceedings},\r\n  ISSN =        {1862-4405},\r\n  publisher =   {Internationales Begegnungs- und Forschungszentrum fuer Informatik (IBFI), \r\n                 Schloss Dagstuhl, Germany},\r\n  OPTaddress =  {Dagstuhl, Germany},\r\n  OPTURL =      {http://drops.dagstuhl.de/opus/volltexte/2005/318\r\n                 [date of citation: 2005-01-01]},\r\n  note =        {$<$http://drops.dagstuhl.de/opus/volltexte/2005/318$>$\r\n                 [date of citation: 2005-01-01]},\r\n  OPTannote =   {Keywords: Annotation, visualization, temporal annotation},\r\n}');
INSERT INTO `refs-history` VALUES (57, 24, 20080109010725, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'Extending TimeML with Typical Durations of Events', 'events ; tarsqi ; timeml', '', '@InProceedings{ pan2006c,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {Extending TimeML with Typical Durations of Events},\r\n  booktitle = {Proceedings of Annotating and Reasoning about Time and Events workshop at\r\n               the 44th Annual Meeting of the Association for Computational Linguistics (COLING-ACL)},\r\n  pages     = {38-45},\r\n  year      = {2006},\r\n  address   = {Sydney, Australia}\r\n}');
INSERT INTO `refs-history` VALUES (58, 25, 20080109011617, 2006, 'James Pustejovsky, Catherine Havasi, Roser Saurí, Patrick Hanks, Anna Rumshisky, Jessica Litman, José Castaño, and Marc Verhagen', 'Towards a Generative Lexical Resource: The Brandeis Semantic Ontology', 'llc', '', '@inproceedings{ bso,\r\n  author    = "James Pustejovsky and Catherine Havasi and Roser Saur\\\'{i} and Patrick Hanks and Anna Rumshisky and Jessica Litman and Jos\\\'{e} Casta{\\~n}o and Marc Verhagen",\r\n  title     = "Towards a {G}enerative {L}exical Resource: {The Brandeis Semantic Ontology}",\r\n  booktitle = "Language Resources and Evaluation Conference, LREC 2006",\r\n  year      = "2006",\r\n  address   = "Genoa, Italy" \r\n}');
INSERT INTO `refs-history` VALUES (59, 25, 20080109011704, 2006, 'James Pustejovsky, Catherine Havasi, Roser Saurí, Patrick Hanks, Anna Rumshisky, Jessica Litman, José Castaño, and Marc Verhagen', 'Towards a Generative Lexical Resource: The Brandeis Semantic Ontology', 'llc ; resources', '', '@inproceedings{ bso,\r\n  author    = "James Pustejovsky and Catherine Havasi and Roser Saur\\\'{i} and Patrick Hanks and Anna Rumshisky and Jessica Litman and Jos\\\'{e} Casta{\\~n}o and Marc Verhagen",\r\n  title     = "Towards a {G}enerative {L}exical Resource: {The Brandeis Semantic Ontology}",\r\n  booktitle = "Language Resources and Evaluation Conference, LREC 2006",\r\n  year      = "2006",\r\n  address   = "Genoa, Italy" \r\n}');
INSERT INTO `refs-history` VALUES (60, 26, 20080109011914, 2006, 'Anna Rumshisky, Patrick Hanks, Catherine Havasi, and James Pustejovsky', 'Constructing a Corpus-based Ontology using Model Bias', 'resources ; tarsqi', '', '@inproceedings{ flairs06,\r\n  author    = "Anna Rumshisky and Patrick Hanks and Catherine Havasi and James Pustejovsky",\r\n  title     = "Constructing a Corpus-based Ontology using Model Bias",\r\n  booktitle = "The 19th International {FLAIRS} Conference, {FLAIRS 2006}",\r\n  year      = "2006",\r\n  address   = " Melbourne Beach, Florida, USA" \r\n}');
INSERT INTO `refs-history` VALUES (61, 27, 20080109024917, 2006, 'Inderjeet Mani, Ben Wellner, Marc Verhagen, Chong Min Lee, and James Pustejovsky', 'Machine Learning of Temporal Relations', 'machine learning ; tarsqi ; temporal links', '', '@inproceedings{ Mani2006,\r\n  author       = {Inderjeet Mani and Ben Wellner and Marc Verhagen and Chong Min Lee and James Pustejovsky},\r\n  year         = "2006",\r\n  title        = {Machine Learning of Temporal Relations},\r\n  booktitle    = {Proceedings of the 44th Annual Meeting of the Association for Computational Linguistics},\r\n  organization = "ACL", \r\n  address      = "Sydney"\r\n}');
INSERT INTO `refs-history` VALUES (62, 28, 20080109032320, 2004, 'ames Pustejovsky, Roser Saurí, José Castaño, Dragomir Radev, Robert Gaizauskas, Andrea Setzer, Beth Sundheim, and Graham Katz', 'Representing Temporal and Event Knowledge for QA Systems', 'events ; llc ; tarsqi ; temporal links ; time expressions', '  ', '@incollection{{Pustejovsky:04,\r\n  author   = "James Pustejovsky and Roser Saur\\\'{\\i} and Jos{\\\'e} Casta\\~{n}o \r\n              and Dragomir Radev and Robert Gaizauskas and Andrea Setzer \r\n              and Beth Sundheim and Graham Katz"\r\n  title     = {Representing Temporal and Event Knowledge for QA Systems},\r\n  year      =  "2004",\r\n  editor    = "Mark T. Maybury",\r\n  booktitle = {New Directions in Question Answering},\r\n  publisher = "MIT Press", \r\n  address   = Cambridge.\r\n}');
INSERT INTO `refs-history` VALUES (63, 28, 20080109032421, 2004, 'James Pustejovsky, Roser Saurí, José Castaño, Dragomir Radev, Robert Gaizauskas, Andrea Setzer, Beth Sundheim, and Graham Katz', 'Representing Temporal and Event Knowledge for QA Systems', 'events ; llc ; tarsqi ; temporal links ; time expressions', '  ', '@incollection{{Pustejovsky:04,\r\n  author   = "James Pustejovsky and Roser Saur\\\'{\\i} and Jos{\\\'e} Casta\\~{n}o \r\n              and Dragomir Radev and Robert Gaizauskas and Andrea Setzer \r\n              and Beth Sundheim and Graham Katz"\r\n  title     = {Representing Temporal and Event Knowledge for QA Systems},\r\n  year      =  "2004",\r\n  editor    = "Mark T. Maybury",\r\n  booktitle = {New Directions in Question Answering},\r\n  publisher = "MIT Press", \r\n  address   = Cambridge.\r\n}');
INSERT INTO `refs-history` VALUES (64, 22, 20080109101640, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'Learning Event Durations from Event Descriptions', 'annotation ; events ; machine learning ; tarsqi', '', '@InProceedings{ pan2006a,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {Learning Event Durations from Event Descriptions},\r\n  booktitle = {Proceedings of the 44th Annual Meeting of the Association for \r\n               Computational Linguistics (COLING-ACL)},\r\n  pages     = {393-400},\r\n  year      = {2006},\r\n  address   = {Sydney, Australia}\r\n}');
INSERT INTO `refs-history` VALUES (65, 25, 20080109113953, 2006, 'James Pustejovsky, Catherine Havasi, Roser Saurí, Patrick Hanks, Anna Rumshisky, Jessica Litman, José Castaño, and Marc Verhagen', 'Towards a Generative Lexical Resource: The Brandeis Semantic Ontology', 'llc ; resources', '', '@inproceedings{ bso,\r\n  author    = "James Pustejovsky and Catherine Havasi and Roser Saur\\\'{i} \r\n               and Patrick Hanks and Anna Rumshisky and Jessica Litman \r\n               and Jos\\\'{e} Casta{\\~n}o and Marc Verhagen",\r\n  title     = "Towards a {G}enerative {L}exical Resource: {The Brandeis Semantic Ontology}",\r\n  booktitle = "Language Resources and Evaluation Conference, LREC 2006",\r\n  year      = "2006",\r\n  address   = "Genoa, Italy" \r\n}');

# --------------------------------------------------------

#
# Table structure for table `refs-keywords`
#

DROP TABLE IF EXISTS `refs-keywords`;
CREATE TABLE `refs-keywords` (
  `keyword` varchar(100) NOT NULL default '',
  `description` varchar(255) NOT NULL default ''
) TYPE=MyISAM;

#
# Dumping data for table `refs-keywords`
#

INSERT INTO `refs-keywords` VALUES ('annotation', '');
INSERT INTO `refs-keywords` VALUES ('temporal reasoning', '');
INSERT INTO `refs-keywords` VALUES ('events', '');
INSERT INTO `refs-keywords` VALUES ('time expressions', '');
INSERT INTO `refs-keywords` VALUES ('timeml', '');
INSERT INTO `refs-keywords` VALUES ('temporal links', '');
INSERT INTO `refs-keywords` VALUES ('tarsqi', 'papers from the tarsqi project (including terqas and tango)');
INSERT INTO `refs-keywords` VALUES ('visualization', '');
INSERT INTO `refs-keywords` VALUES ('tools', '');
INSERT INTO `refs-keywords` VALUES ('llc', 'papers by llc members');
INSERT INTO `refs-keywords` VALUES ('machine learning', '');
INSERT INTO `refs-keywords` VALUES ('resources', 'corpora, ontologies, lexicons etcetera');
INSERT INTO `refs-keywords` VALUES ('evaluation', '');
INSERT INTO `refs-keywords` VALUES ('question answering', '');

# --------------------------------------------------------

#
# Table structure for table `refs-main`
#

DROP TABLE IF EXISTS `refs-main`;
CREATE TABLE `refs-main` (
  `id` int(11) NOT NULL auto_increment,
  `year` smallint(6) NOT NULL default '0',
  `author` varchar(255) NOT NULL default '',
  `title` varchar(255) NOT NULL default '',
  `keywords` varchar(255) NOT NULL default '',
  `html` text NOT NULL,
  `bibtex` text NOT NULL,
  PRIMARY KEY  (`id`)
) TYPE=MyISAM AUTO_INCREMENT=29 ;

#
# Dumping data for table `refs-main`
#

INSERT INTO `refs-main` VALUES (6, 1997, 'David Day, John Aberdeen, Lynette Hirschman, Robyn Kozierok, Patricia Robinson, and Marc Vilain', 'Mixed-Initiative Development of Language Processing Systems', 'annotation ; tools', '', '@inproceedings{Alembic,\r\n  author	= "David Day and John Aberdeen and Lynette Hirschman and Robyn Kozierok\r\n                   and Patricia Robinson and Marc Vilain",\r\n  title		= "{Mixed-Initiative Development of Language Processing Systems}",\r\n  booktitle	= "Fifth Conference on Applied Natural Language Processing Systems",\r\n  year		= "1997",\r\n  pages		= "88--95",\r\n  address	= "Washington D.C., U.S.A."\r\n}');
INSERT INTO `refs-main` VALUES (7, 2005, 'Marc Verhagen', 'Drawing TimeML Relations with T-BOX', 'tarsqi ; temporal reasoning ; timeml ; tools ; visualization', '', '@InProceedings{verhagen:2005b,\r\n  author =      {Marc Verhagen},\r\n  title =       {Drawing {T}ime{ML} Relations with {T-BOX}},\r\n  booktitle =   {Annotating, Extracting and Reasoning about Time and Events},\r\n  year =        {2005},\r\n  editor =      {Graham Katz and James Pustejovsky and Frank Schilder},\r\n  number =      {05151},\r\n  series =      {Dagstuhl Seminar Proceedings},\r\n  ISSN =        {1862-4405},\r\n  publisher =   {Internationales Begegnungs- und Forschungszentrum fuer Informatik (IBFI), \r\n                 Schloss Dagstuhl, Germany},\r\n  OPTaddress =  {Dagstuhl, Germany},\r\n  OPTURL =      {http://drops.dagstuhl.de/opus/volltexte/2005/318\r\n                 [date of citation: 2005-01-01]},\r\n  note =        {$<$http://drops.dagstuhl.de/opus/volltexte/2005/318$>$\r\n                 [date of citation: 2005-01-01]},\r\n  OPTannote =   {Keywords: Annotation, visualization, temporal annotation},\r\n}');
INSERT INTO `refs-main` VALUES (8, 2005, 'Marc Verhagen, Inderjeet Mani, Roser Sauri, Jessica Littman, Robert Knippen, Seok Bae Jang, Anna Rumshisky, John Phillips, and James Pustejovsky', 'Automating Temporal Annotation with TARSQI', 'annotation ; tarsqi ; temporal links ; timeml', '', '@inproceedings{tarsqi:2005,\r\n  author    = {Marc Verhagen and Inderjeet Mani and Roser Sauri and Jessica Littman \r\n               and Robert Knippen and Seok Bae Jang and Anna Rumshisky and John Phillips \r\n               and James Pustejovsky},\r\n  title     = {Automating Temporal Annotation with {TARSQI}},\r\n  booktitle = "Proceedings of the 43th Annual Meeting of the Association for \r\n               Computational Linguistics",\r\n  year      = 2005,\r\n  note      = "Demo session",\r\n  address   = "Ann Arbor, USA"\r\n}');
INSERT INTO `refs-main` VALUES (9, 2002, 'James Pustejovsky, Luc Belanger, José Castaño, Robert Gaizauskas, Patrick Hanks, Bob Ingria, Graham Katz, Dragomir Radev, Anna Rumshishky, Antonio Sanfilippo, Roser Saurí, Andrea Setzer, Beth Sundheim, Marc Verhagen', 'TERQAS Final Report', 'annotation ; events ; llc ; tarsqi ; temporal links ; time expressions ; tools', '', '@techreport{Terqas:2002,\r\n  author      	= "James Pustejovsky and Luc Belanger and Jose Casta{\\~n}o \r\n                   and Robert Gaizauskas and Patrick Hanks and Bob Ingria \r\n                   and Graham Katz and Dragomir Radev and Anna Rumshishky \r\n                   and Antonio Sanfilippo and Roser Saur{\\\'i} and Andrea Setzer \r\n                   and Beth Sundheim and Marc Verhagen",\r\n  title       	= "{TERQAS Final Report}",\r\n  year        	= 2002,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-main` VALUES (10, 2003, 'James Pustejovsky, Inderjeet Mani, Luc Belanger, Linda van Guilder, Robert Knippen, Andrew See, Jon Schwarz, and Marc Verhagen', 'TANGO Final Report', 'annotation ; llc ; tarsqi ; tools ; visualization', '', '@techreport{Tango:2003,\r\n  author      	= "James Pustejovsky and Inderjeet Mani and Luc Belanger \r\n                   and Linda van Guilder and Robert Knippen and Andrew See \r\n                   and Jon Schwarz and Marc Verhagen",\r\n  title       	= "{TANGO Final Report}",\r\n  year        	= 2003,\r\n  institution 	= "The MITRE Corporation",\r\n  address	= "Bedford, Massachusetts"\r\n}');
INSERT INTO `refs-main` VALUES (11, 2003, 'David Day, Lisa Ferro, Robert Gaizauskas, Patrick Hanks, Marcia Lazo, James Pustejovsky, Roser Saurí, Andrew See, Andrea Setzer, and Beth Sundheim', 'The TimeBank Corpus', 'annotation ; llc ; tarsqi ; timeml', '', '@article{TimeBank,\r\n  author	= "David Day and Lisa Ferro and Robert Gaizauskas and Patrick Hanks \r\n                   and Marcia Lazo and James Pustejovsky and Roser Saur{\\\'i} \r\n                   and Andrew See and Andrea Setzer and Beth Sundheim",\r\n  title		= "{The TimeBank Corpus}",\r\n  journal	= "Corpus Linguistics",\r\n  year		= 2003,\r\n  month		= "March",\r\n  address	= "Lancaster, UK"\r\n}');
INSERT INTO `refs-main` VALUES (12, 2003, 'James Pustejovsky, José Castaño, Robert Ingria, Roser Saurí, Robert Gaizauskas, Andrea Setzer, and Graham Katz', 'TimeML: Robust Specification of Event and Temporal Expressions in Text', 'llc ; tarsqi ; timeml', '', '@inproceedings{TimeML,\r\n  author	= "James Pustejovsky and Jos{\\\'e} Casta{\\~n}o and Robert Ingria \r\n                   and Roser Saur{\\\'i} and Robert Gaizauskas and Andrea Setzer \r\n                   and Graham Katz",\r\n  title		= "{TimeML: Robust Specification of Event and Temporal Expressions in Text}",\r\n  booktitle	= "IWCS-5 Fifth International Workshop on Computational Semantics",\r\n  year		= 2003\r\n}');
INSERT INTO `refs-main` VALUES (22, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'Learning Event Durations from Event Descriptions', 'annotation ; events ; machine learning ; tarsqi', '', '@InProceedings{ pan2006a,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {Learning Event Durations from Event Descriptions},\r\n  booktitle = {Proceedings of the 44th Annual Meeting of the Association for \r\n               Computational Linguistics (COLING-ACL)},\r\n  pages     = {393-400},\r\n  year      = {2006},\r\n  address   = {Sydney, Australia}\r\n}');
INSERT INTO `refs-main` VALUES (14, 2005, 'Marc Verhagen', 'Temporal Closure in an Annotation Environment', 'annotation ; temporal links ; temporal reasoning ; tools', 'Marc Verhagen. 2005. Temporal Closure in an Annotation Environment. <i>Language Resources and Evaluation</i>, Volume 39, May 2005, pp 211-241, Springer.', '@article{closure:2005,\r\n  author    = "Marc Verhagen",\r\n  title     = "Temporal Closure in an Annotation Environment",\r\n  journal   = "Language Resources and Evaluation",\r\n  year      = 2005,\r\n  month     = May,\r\n  volume    = 39,\r\n  pages     = "211-241",\r\n  publisher = "Springer"\r\n}');
INSERT INTO `refs-main` VALUES (15, 2005, 'James Pustejovsky, Robert Knippen, Jessica Littman, and Roser Saurí', 'Temporal and Event Information in Natural Language Text', 'annotation ; events ; time expressions ; timeml', '', '@article{timeml:2005,\r\n  author = "James Pustejovsky and Robert Knippen and Jessica Littman and Roser Saur\\\'i",\r\n  title = "Temporal and Event Information in Natural Language Text",\r\n  journal = "Language Resources and Evaluation",\r\n  year = 2005,\r\n  month = May,\r\n  volume = 39,\r\n  pages = "123-164",\r\n  publisher = "Springer"\r\n}');
INSERT INTO `refs-main` VALUES (16, 2005, 'Dick Crouch, Roser Saurí, and Abraham Fowler', 'AQUAINT Pilot Knowledge-Based Evaluation: Annotation Guidelines', 'annotation ; llc ; tarsqi', '', '@techreport{kb-eval,\r\n  author = "Dick Crouch and Roser Saur\\\'{\\i} and Abraham Fowler",\r\n  title = "AQUAINT Pilot Knowledge-Based Evaluation: Annotation Guidelines",\r\n  year = 2005,\r\n  month = May,\r\n  institution = "Palo Alto Research Center"\r\n}');
INSERT INTO `refs-main` VALUES (17, 2005, 'Roser Saurí and Marc Verhagen', 'Temporal Information in Intensional Contexts', 'temporal links ; timeml', '', '@inproceedings{slinket-iwcs05,\r\n  author    = "Roser Saur{\\\'i} and Marc Verhagen",\r\n  title     = "Temporal Information in Intensional Contexts",\r\n  booktitle = "Proceedings of the Sixth International Workshop on Computation Semantics (IWCS-6)",\r\n  year      = 2005,\r\n  address   = "Tilburg, Netherlands"\r\n}');
INSERT INTO `refs-main` VALUES (18, 2005, 'Roser Saurí, Robert Knippen, Marc Verhagen, and James Pustejovsky', 'Evita: A Robust Event Recognizer For QA Systems', 'events ; tarsqi ; timeml', '', '@inproceedings{evita-htl05,\r\n  author = "Roser Saur{\\\'i} and Robert Knippen and Marc Verhagen and James Pustejovsky",\r\n  title = "{Evita}: A Robust Event Recognizer For QA Systems",\r\n  booktitle = "Proceedings of the HLT/EMNLP 2005",\r\n  pages = "700-707",\r\n  year = 2005\r\n}');
INSERT INTO `refs-main` VALUES (19, 2006, 'Roser Saurí, Marc Verhagen, and James Pustejovsky', 'Annotating and Recognizing Event Modality in Text', 'events ; tarsqi', '', '@inproceedings{evita-aaai06,\r\n  author    = "Roser Saur{\\\'i} and Marc Verhagen and James Pustejovsky",\r\n  title     = "Annotating and Recognizing Event Modality in Text",\r\n  booktitle = "(AAAI 2006)",\r\n  year      = 2006\r\n}');
INSERT INTO `refs-main` VALUES (20, 2006, 'Roser Saurí, Marc Verhagen, and James Pustejovsky', 'SlinkET: A Partial Modal Parser for Events', 'events ; tarsqi ; temporal links ; tools', '', '@inproceedings{slinket-lrec,\r\n  author    = "Roser Saur{\\\'i} and Marc Verhagen and James Pustejovsky",\r\n  title     = "{SlinkET}: A Partial Modal Parser for Events",\r\n  booktitle = "Language Resources and Evaluation Conference, {LREC 2006}",\r\n  year      = "2006",\r\n  address   = "Genoa, Italy" \r\n}');
INSERT INTO `refs-main` VALUES (21, 2006, 'Marc Verhagen, Robert Knippen, Inderjeet Mani, and James Pustejovsky', 'Annotation of Temporal Relations with Tango', 'annotation ; tarsqi ; temporal links ; tools', '', '@inproceedings{tango-lrec,\r\n  author = "Marc Verhagen and Robert Knippen and Inderjeet Mani and James Pustejovsky",\r\n  title = "Annotation of Temporal Relations with {Tango}",\r\n  booktitle = "Language Resources and Evaluation Conference, {LREC 2006}",\r\n  year = "2006",\r\n  address = "Genoa, Italy" \r\n}');
INSERT INTO `refs-main` VALUES (23, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'An Annotated Corpus of Typical Durations of Events', 'annotation ; events ; tarsqi', '', '@InProceedings{ pan2006b,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {An Annotated Corpus of Typical Durations of Events},\r\n  booktitle = {Proceedings of the Fifth International Conference on Language Resources and Evaluation (LREC)},\r\n  pages     = {77-83},\r\n  year      = {2006},\r\n  address   = {Genoa, Italy}\r\n}');
INSERT INTO `refs-main` VALUES (24, 2006, 'Feng Pan, Rutu Mulkar, and Jerry R. Hobbs', 'Extending TimeML with Typical Durations of Events', 'events ; tarsqi ; timeml', '', '@InProceedings{ pan2006c,\r\n  author    = {Feng Pan and Rutu Mulkar and Jerry R. Hobbs},\r\n  title     = {Extending TimeML with Typical Durations of Events},\r\n  booktitle = {Proceedings of Annotating and Reasoning about Time and Events workshop at\r\n               the 44th Annual Meeting of the Association for Computational Linguistics (COLING-ACL)},\r\n  pages     = {38-45},\r\n  year      = {2006},\r\n  address   = {Sydney, Australia}\r\n}');
INSERT INTO `refs-main` VALUES (25, 2006, 'James Pustejovsky, Catherine Havasi, Roser Saurí, Patrick Hanks, Anna Rumshisky, Jessica Litman, José Castaño, and Marc Verhagen', 'Towards a Generative Lexical Resource: The Brandeis Semantic Ontology', 'llc ; resources', '', '@inproceedings{ bso,\r\n  author    = "James Pustejovsky and Catherine Havasi and Roser Saur\\\'{i} \r\n               and Patrick Hanks and Anna Rumshisky and Jessica Litman \r\n               and Jos\\\'{e} Casta{\\~n}o and Marc Verhagen",\r\n  title     = "Towards a {G}enerative {L}exical Resource: {The Brandeis Semantic Ontology}",\r\n  booktitle = "Language Resources and Evaluation Conference, LREC 2006",\r\n  year      = "2006",\r\n  address   = "Genoa, Italy" \r\n}');
INSERT INTO `refs-main` VALUES (26, 2006, 'Anna Rumshisky, Patrick Hanks, Catherine Havasi, and James Pustejovsky', 'Constructing a Corpus-based Ontology using Model Bias', 'resources ; tarsqi', '', '@inproceedings{ flairs06,\r\n  author    = "Anna Rumshisky and Patrick Hanks and Catherine Havasi and James Pustejovsky",\r\n  title     = "Constructing a Corpus-based Ontology using Model Bias",\r\n  booktitle = "The 19th International {FLAIRS} Conference, {FLAIRS 2006}",\r\n  year      = "2006",\r\n  address   = " Melbourne Beach, Florida, USA" \r\n}');
INSERT INTO `refs-main` VALUES (27, 2006, 'Inderjeet Mani, Ben Wellner, Marc Verhagen, Chong Min Lee, and James Pustejovsky', 'Machine Learning of Temporal Relations', 'machine learning ; tarsqi ; temporal links', '', '@inproceedings{ Mani2006,\r\n  author       = {Inderjeet Mani and Ben Wellner and Marc Verhagen and Chong Min Lee and James Pustejovsky},\r\n  year         = "2006",\r\n  title        = {Machine Learning of Temporal Relations},\r\n  booktitle    = {Proceedings of the 44th Annual Meeting of the Association for Computational Linguistics},\r\n  organization = "ACL", \r\n  address      = "Sydney"\r\n}');
INSERT INTO `refs-main` VALUES (28, 2004, 'James Pustejovsky, Roser Saurí, José Castaño, Dragomir Radev, Robert Gaizauskas, Andrea Setzer, Beth Sundheim, and Graham Katz', 'Representing Temporal and Event Knowledge for QA Systems', 'events ; llc ; tarsqi ; temporal links ; time expressions', '  ', '@incollection{{Pustejovsky:04,\r\n  author   = "James Pustejovsky and Roser Saur\\\'{\\i} and Jos{\\\'e} Casta\\~{n}o \r\n              and Dragomir Radev and Robert Gaizauskas and Andrea Setzer \r\n              and Beth Sundheim and Graham Katz"\r\n  title     = {Representing Temporal and Event Knowledge for QA Systems},\r\n  year      =  "2004",\r\n  editor    = "Mark T. Maybury",\r\n  booktitle = {New Directions in Question Answering},\r\n  publisher = "MIT Press", \r\n  address   = Cambridge.\r\n}');

# --------------------------------------------------------

#
# Table structure for table `refs-notes`
#

DROP TABLE IF EXISTS `refs-notes`;
CREATE TABLE `refs-notes` (
  `id` int(11) NOT NULL auto_increment,
  `refid` int(11) NOT NULL default '0',
  `timestamp` timestamp(14) NOT NULL,
  `note` text NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `refid` (`refid`)
) TYPE=MyISAM AUTO_INCREMENT=3 ;

#
# Dumping data for table `refs-notes`
#

INSERT INTO `refs-notes` VALUES (2, 28, 20080109032320, 'José Castaño');
    

